# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GyvYAiFKrTKN8tKA2tAyh39df5YKnbpV
"""

from google.colab import drive
drive.mount('/content/drive')


import streamlit as st
import pickle
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

tfidf=pickle.load(open('/content/drive/MyDrive/Colab Notebooks/tfidf.pkl','rb'))
model=pickle.load(open('/content/drive/MyDrive/Colab Notebooks/lr.pkl','rb'))

st.title("Movie Review Sentiment Analysis")
user_input=st.text_area("Enter your review here:")
input_vec=tfidf.transform([user_input])

if st.button("Predict"):
  if user_input.strip()=="":
    st.warning("Please enter a review")
  else:
    prediction=model.predict(input_vec)[0]
    st.success(f"Predicted Sentiment: {prediction}")

analyzer=SentimentIntensityAnalyzer()
score=analyzer.polarity_scores(user_input)['compound']

if score>0.05:
  rule_sentiment="Positive"
elif score<-0.05:
  rule_sentiment="Negative"
else:
  rule_sentiment="Neutral"

st.info(f"Rule-based Sentiment: {rule_sentiment}")

confidence =max(model.decision_function(input_vec)[0])
st.write(f"Confidence: {confidence:.2f}")

